### ISSUE TITLE
Roadmap - v0.1.0

### ISSUE THREAD

**Issue by Jarmos-san** [Weburz/terox#18]
The following features of Terox are planned to be released for the first stable release:

- [x] Print useful version information (including the commit hash and build date info for user reference).
- [ ] Functionality to download and scaffold projects using templates.
  - [ ] Download the template as a zipped file from a GitHub repository.
  - [ ] Extract the zipped template to disk on the user's system.
- [ ] Ability to generate templates.
- [ ] ABility to configure Terox using YAML, JSON (and possible TOML) files.

These functionalities are subject to change, so if you feel some features are missing out in the first release, then leave a comment below and it will be evaluated for addition to the release.
